
//////////////////// STRINGS

const Strings = {

    "ST1": "AffiLink",
    "ST2": "Home",
    "ST3": "Search",
    "ST4": "Favorites",
    "ST5": "Shop",
    "ST6": "Profile",
    "ST7": "Contact Us",
    "ST8": "Terms and Conditions",
    "ST9": "Sign Out",
    "ST10": "Sign In",
    "ST11": "Sign Up",
    "ST12": "Don't have an account?",
    "ST13": "Already have an account?",
    "ST14": "I Agree to Terms and Conditions",
    "ST15": "Forgot Password?",
    "ST16": "Need Help? Contact Us",
    "ST17": "Enter",
    "ST18": "Name",
    "ST19": "Email",
    "ST20": "Password (Length 8-32)",
    "ST21": "Search...",
    "ST22": "Exclusive Deals",
    "ST23": "Explore By Stores",
    "ST24": "Explore Categories",
    "ST25": "Latest Deals",
    "ST26": "Shop Today's Trending Deals and Save Big",
    "ST27": "Over 20 000+ deals. Grab one now!",
    "ST28": "Categories",
    "ST29": "Exclusive",
    "ST30": "No Content Found",
    "ST31": "Please Wait...",
    "ST32": "Something Wrong",
    "ST33": "Please Complete The Form",
    "ST34": "Sign In",
    "ST35": "Sign Up",
    "ST36": "Email Already Exists",
    "ST37": "Email Doesn't Exist",
    "ST38": "Password Updated",
    "ST39": "Password Reset Email Sent",
    "ST40": "Ok",
    "ST41": "Sub Categories",
    "ST42": "Contact Us",
    "ST43": "Reset Password",
    "ST44": "Any",
    "ST45": "Featured Deals",
    "ST46": "Explore Cities Differently",
    "ST47": "Top Rated",
    "ST48": "No Results Found",
    "ST49": "Days",
    "ST50": "Hours",
    "ST51": "Minutes",
    "ST52": "Seconds",
    "ST53": "Buy Now",
    "ST54": "Review(s)",
    "ST55": "Write Review",
    "ST56": "You have already submitted a review",
    "ST57": "Your review has been submitted and awaiting moderation.",
    "ST58": "Reviews",
    "ST59": "Stores",
    "ST60": "Locations",
    "ST65": "Ooops! No Results",
    "ST66": "Try different keywords or remove search filters",
    "ST67": "Results",
    "ST68": "Total",
    "ST69": "Categories",
    "ST70": "Show Results",
    "ST71": "Price",
    "ST72": "Sub Categories",
    "ST74": "Try Again",
    "ST76": "Done",
    "ST77": "Cancel",
    "ST78": "Save",
    "ST85": "Rating",
    "ST88": "Reviews",
    "ST89": "Show Comments",
    "ST90": "No Comments Found",
    "ST91": "Submit Comment",
    "ST92": "Share",
    "ST96": "Submit",
    "ST97": "Thank You",
    "ST98": "Exlusive Content",
    "ST99": "Only registered users can see the exclusive deals",
    "ST100": "Get In Touch",
    "ST101": "Use the form below to drop us an e-mail",
    "ST102": "View other replies",
    "ST103": "Your Comment",
    "ST104": "Error",
    "ST105": "You have requested too many password resets.",
    "ST106": "Remove",
    "ST108": "My Recipes",
    "ST110": "About Us",
    "ST111": "Load More...",
    "ST112": "No More Items",
    "ST113": "All"

};

export default Strings;
